kind: Service
apiVersion: v1
metadata:
  name: deployment-example
  namespace: dev07
  labels:
    app: deployment-example
    app.kubernetes.io/component: deployment-example
    app.kubernetes.io/instance: deployment-example
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentconfig: deployment-example